name: OmniGPS
options:
  bundleIdPrefix: com.omni
targets:
  OmniGPS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - main.m
      - AppDelegate.h
      - AppDelegate.m
      - ViewController.h
      - ViewController.m
      - Resources
    settings:
      base:
        CODE_SIGNING_ALLOWED: NO
        DONT_CODE_SIGN: YES
        INFOPLIST_FILE: Resources/Info.plist
        OTHER_LDFLAGS: -framework UIKit -framework UniformTypeIdentifiers -framework CoreLocation
