name: OmniGPS
options:
  bundleIdPrefix: com.omni
targets:
  OmniGPS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - main.m
      - AppDelegate.h
      - AppDelegate.m
      - ViewController.h
      - ViewController.m
      - Resources
    settings:
      base:
        CODE_SIGNING_ALLOWED: NO
        DONT_CODE_SIGN: YES
        INFOPLIST_FILE: Resources/Info.plist
        OTHER_LDFLAGS: -framework UIKit -framework UniformTypeIdentifiers -framework CoreLocation
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: NO
        
        # 🚀 TUYỆT CHIÊU MỞ KHÓA: Ép app mở quyền mở và đọc TẤT CẢ các loại định dạng file trên iPhone (Chống block file gpx)
        INFOPLIST_KEY_CFBundleDocumentTypes:
          - CFBundleTypeName: "All Files"
            LSHandlerRank: "Owner"
            LSItemContentTypes:
              - "public.data"
              - "public.item"
              - "public.content"
              - "public.xml"
